/**
 * Presto API
 * Presto API Coding Challenge
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mark.hary@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Item'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Item'));
  } else {
    // Browser globals (root is window)
    if (!root.PrestoApi) {
      root.PrestoApi = {};
    }
    root.PrestoApi.RestaurantApi = factory(root.PrestoApi.ApiClient, root.PrestoApi.Item);
  }
}(this, function(ApiClient, Item) {
  'use strict';

  /**
   * Restaurant service.
   * @module api/RestaurantApi
   * @version 1.0.0
   */

  /**
   * Constructs a new RestaurantApi. 
   * @alias module:api/RestaurantApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getItemsById operation.
     * @callback module:api/RestaurantApi~getItemsByIdCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Item>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrive list of menu items available at restaurant
     * Returns a list of menu items
     * @param {Number} restaurantID ID of restaurant to retrieve
     * @param {module:api/RestaurantApi~getItemsByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Item>}
     */
    this.getItemsById = function(restaurantID, callback) {
      var postBody = null;

      // verify the required parameter 'restaurantID' is set
      if (restaurantID === undefined || restaurantID === null) {
        throw new Error("Missing the required parameter 'restaurantID' when calling getItemsById");
      }


      var pathParams = {
        'restaurantID': restaurantID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Item];

      return this.apiClient.callApi(
        '/restaurant/{restaurantID}/item', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
