---
swagger: "2.0"
info:
  description: "Presto API Coding Challenge"
  version: "1.0.0"
  title: "Presto API"
  contact:
    email: "mark.hary@gmail.com"
  license:
    name: "Unlicense"
    url: "https://unlicense.org"
tags:
- name: "restaurant"
  description: "Menu items available for your restaurant"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/markhary/presto"
schemes:
- "http"
paths:
  /restaurant/{restaurantID}/item:
    get:
      tags:
      - "restaurant"
      summary: "Retrive list of menu items available at restaurant"
      description: "Returns a list of menu items"
      operationId: "getItemsById"
      produces:
      - "application/json"
      parameters:
      - name: "restaurantID"
        in: "path"
        description: "ID of restaurant to retrieve"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Item"
            example:
            - id: 1
              name: "Hamburger"
              description: "Sandwich with meat"
              modifiers:
              - id: 100
                name: "Ketchup"
                description: "Tomato sauce with sugar"
              - id: 101
                name: "Lettuce"
                description: "Leafy"
            - id: 2
              name: "French fries"
              description: "Potatoes done properly"
            - id: 3
              name: "Salad"
              description: "More greenery"
              modifiers:
              - id: 300
                name: "Blue Cheese Dressing"
                description: "With blue cheese"
                modifiers:
                - id: 3000
                  name: "Extra blue cheese"
                  description: "Can't get enough"
              - id: 301
                name: "Oil and Vinegar"
                description: "A trusted classic"
              - id: 302
                name: "Thousand Island Dressing"
                description: "Because 999 Island sucked"
        400:
          description: "Invalid RestaurantID supplied"
        404:
          description: "RestaurantID not found"
      x-swagger-router-controller: "Restaurant"
definitions:
  Item:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      modifiers:
        type: "array"
        items:
          $ref: "#/definitions/Item"
    xml:
      name: "Item"
externalDocs:
  description: "Find out more about this challenge"
  url: "https://github.com/markhary/presto"
